// Generated by scripts/render-chords.mjs (`npm run render:chords`) — don't edit by hand.
import type { Letter, Mode } from "@/data/notes";
import type { Instrument } from "./instruments";

export const CHORDS: Record<Instrument, Record<Letter, Record<Mode, number>>> = {
  piano: {
    C: { major: require("../../assets/sounds/piano/c-major.wav"), minor: require("../../assets/sounds/piano/c-minor.wav") },
    D: { major: require("../../assets/sounds/piano/d-major.wav"), minor: require("../../assets/sounds/piano/d-minor.wav") },
    E: { major: require("../../assets/sounds/piano/e-major.wav"), minor: require("../../assets/sounds/piano/e-minor.wav") },
    F: { major: require("../../assets/sounds/piano/f-major.wav"), minor: require("../../assets/sounds/piano/f-minor.wav") },
    G: { major: require("../../assets/sounds/piano/g-major.wav"), minor: require("../../assets/sounds/piano/g-minor.wav") },
    A: { major: require("../../assets/sounds/piano/a-major.wav"), minor: require("../../assets/sounds/piano/a-minor.wav") },
    B: { major: require("../../assets/sounds/piano/b-major.wav"), minor: require("../../assets/sounds/piano/b-minor.wav") },
  },
  violin: {
    C: { major: require("../../assets/sounds/violin/c-major.wav"), minor: require("../../assets/sounds/violin/c-minor.wav") },
    D: { major: require("../../assets/sounds/violin/d-major.wav"), minor: require("../../assets/sounds/violin/d-minor.wav") },
    E: { major: require("../../assets/sounds/violin/e-major.wav"), minor: require("../../assets/sounds/violin/e-minor.wav") },
    F: { major: require("../../assets/sounds/violin/f-major.wav"), minor: require("../../assets/sounds/violin/f-minor.wav") },
    G: { major: require("../../assets/sounds/violin/g-major.wav"), minor: require("../../assets/sounds/violin/g-minor.wav") },
    A: { major: require("../../assets/sounds/violin/a-major.wav"), minor: require("../../assets/sounds/violin/a-minor.wav") },
    B: { major: require("../../assets/sounds/violin/b-major.wav"), minor: require("../../assets/sounds/violin/b-minor.wav") },
  },
  harp: {
    C: { major: require("../../assets/sounds/harp/c-major.wav"), minor: require("../../assets/sounds/harp/c-minor.wav") },
    D: { major: require("../../assets/sounds/harp/d-major.wav"), minor: require("../../assets/sounds/harp/d-minor.wav") },
    E: { major: require("../../assets/sounds/harp/e-major.wav"), minor: require("../../assets/sounds/harp/e-minor.wav") },
    F: { major: require("../../assets/sounds/harp/f-major.wav"), minor: require("../../assets/sounds/harp/f-minor.wav") },
    G: { major: require("../../assets/sounds/harp/g-major.wav"), minor: require("../../assets/sounds/harp/g-minor.wav") },
    A: { major: require("../../assets/sounds/harp/a-major.wav"), minor: require("../../assets/sounds/harp/a-minor.wav") },
    B: { major: require("../../assets/sounds/harp/b-major.wav"), minor: require("../../assets/sounds/harp/b-minor.wav") },
  },
  flute: {
    C: { major: require("../../assets/sounds/flute/c-major.wav"), minor: require("../../assets/sounds/flute/c-minor.wav") },
    D: { major: require("../../assets/sounds/flute/d-major.wav"), minor: require("../../assets/sounds/flute/d-minor.wav") },
    E: { major: require("../../assets/sounds/flute/e-major.wav"), minor: require("../../assets/sounds/flute/e-minor.wav") },
    F: { major: require("../../assets/sounds/flute/f-major.wav"), minor: require("../../assets/sounds/flute/f-minor.wav") },
    G: { major: require("../../assets/sounds/flute/g-major.wav"), minor: require("../../assets/sounds/flute/g-minor.wav") },
    A: { major: require("../../assets/sounds/flute/a-major.wav"), minor: require("../../assets/sounds/flute/a-minor.wav") },
    B: { major: require("../../assets/sounds/flute/b-major.wav"), minor: require("../../assets/sounds/flute/b-minor.wav") },
  },
};

export const CHIMES = {
  save: require("../../assets/sounds/chimes/save.wav"),
  composed: require("../../assets/sounds/chimes/composed.wav"),
  breatheIn: require("../../assets/sounds/chimes/breatheIn.wav"),
  breatheOut: require("../../assets/sounds/chimes/breatheOut.wav"),
  composing: require("../../assets/sounds/chimes/composing.wav"),
  finish: require("../../assets/sounds/chimes/finish.wav"),
} as const;

export type Chime = keyof typeof CHIMES;
